from constants import TEST_BUILD, HOST_IP, HOST_USER, HOST_PASSWORD, \
    RHVM_FQDN, \
    RHN_USER, RHN_PASSWORD, ACTIVATION_KEY, ACTIVATION_ORG, \
    SATELLITE_IP, SATELLITE_HOSTNAME, SATELLITE_USER, SATELLITE_PASSWORD, CA_PATH, \
    RHVM_APPLIANCE_PATH, NFS_IP, NFS_PASSWORD, HE_INSTALL_NFS, HE_DATA_NFS, \
    HE_VM_MAC, HE_VM_FQDN, HE_VM_IP, HE_VM_PASSWORD, \
    ENGINE_PASSWORD, AUTO_ANSWER, SECOND_HOST, SECOND_PASSWORD, SECOND_VM_FQDN, \
    HE_BVNIC_MAPPER
